### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5.github.io#100]
- [x] Publish to npm
 - [x] Update website
 - Upgrade plugins
   - [x] webpack
   - [x] jest
   - [x] ember-cli
   - [x] broccoli
   - [x] metalsmith
   - [x] gulp
   - [x] gobble
   - [x] brunch
   - [x] browserify
   - [x] karma
   - [x] duo
   - [x] grunt
   - [x] jade
   - [x] connect
   - [x] rails

**Comment by sebmck** [comment]
@guybedford 3.0.0 has been released!

**Comment by sebmck** [comment]
@shinnn Can you please add me as an owner to the `metalsmith-6to5` npm package so I can push a new version?

**Comment by sebmck** [comment]
@stefanpenner I'll leave updating `ember-cli-6to5` to you since I'll probably break something and the version will need to be bumped in `ember-cli` too.

**Comment by sebmck** [comment]
I totally opened this issue in the wrong repo...

**Comment by stefanpenner** [comment]
jumping on ember-cli now

**Comment by shinnn** [comment]
> Can you please add me as an owner to the `metalsmith-6to5` npm package so I can push a new version?

Done.

**Comment by sebmck** [comment]
@shinnn Great, thanks!

**Comment by stefanpenner** [comment]
> jumping on ember-cli now

done, released as 3.0.0. Ember-cli 0.1.10 tonight will likely contain it by default, other users can update independently

**Comment by sebmck** [comment]
Great, thanks everyone!
