### ISSUE TITLE
Example on the compare page is outdated

### ISSUE THREAD

**Issue by FWeinb** [6to5/6to5.github.io#112]
The example on the  [compare page]() is outdated.

You say that 
```js
var seattlers = [for (c of customers) if (c.city == "Seattle") { name: c.name, age: c.age }];
```
will be transformed to:

```js
var seattlers = Array.from(customers).filter(function (c) {
  return c.city == "Seattle";
}).map(function (c) {
  return {
    name: c.name,
    age: c.age
  };
});
```

it does't look that nice anymore.

```js
"use strict";

var seattlers = (function () {
  var _seattlers = [];

  for (var _iterator = customers[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
    var c = _step.value;
    if (c.city == "Seattle") {
      _seattlers.push({ name: c.name, age: c.age });
    }
  }

  return _seattlers;
})();
```
The loose mode is making it even worse I made a simple in the [REPL](http://bit.ly/1Ez56ZN).

**Comment by sebmck** [comment]
Yep, `for...of` looks like crap with loose mode on because you set it to a blanket `all`. It's documented on the [loose mode](http://6to5.org/docs/usage/loose/#for-of) page.

**Comment by sebmck** [comment]
Updated the example to something more current, thanks!

**Comment by FWeinb** [comment]
This is related to #40
