### ISSUE TITLE
repl gets angry if you throw in a finally block

### ISSUE THREAD

**Issue by bmeck** [6to5/6to5.github.io#115]
```
function* f() {
  try {
  }
  finally {
    throw new Error('b');
  }
}
try {
  f().next();
}
catch (e) {
  console.error(e);
}
```

**Comment by thejameskyle** [comment]
This has nothing to do with the `try...finally` it's actually just that `console.error` doesn't exist. See #105

**Comment by sebmck** [comment]
@thejameskyle Yep, I mentioned that in the [original issue](https://github.com/6to5/6to5/issues/671#issuecomment-72550537). Is there another issue currently tracking this?
