### ISSUE TITLE
document all transformers

### ISSUE THREAD

**Issue by aeosynth** [6to5/6to5.github.io#132]
(almost?) everything here: https://github.com/6to5/6to5/blob/master/lib/6to5/transformation/transformers/index.js

should be listed here: http://6to5.org/docs/usage/transformers/

for example, there is no documentation on the minification transformers. even the fact that they exist would be helpful. this could perhaps be auto generated.

**Comment by sebmck** [comment]
@aeosynth If a transformer isn't documented then it's still in development.
