### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by eventualbuddha** [6to5/6to5.github.io#16]
Needs to have a favicon, as this isn't great:

![2015-01-07 at 7 54 am](https://cloud.githubusercontent.com/assets/1938/5648317/6f0ac160-9642-11e4-894b-e21913ee914e.png)

**Comment by thejameskyle** [comment]
Hmm, I'm not sure what it should be because the 6to5 logo would have 1px wide letters.

**Comment by eventualbuddha** [comment]
The fav icon can be up to 64x64, I think.

**Comment by sebmck** [comment]
Even just the number 6 in the current logo would be fine.

**Comment by sparty02** [comment]
@sebmck @thejameskyle Which do you like better?

![image](https://cloud.githubusercontent.com/assets/1483538/5831749/32cdd1c6-a0fe-11e4-8b92-ebe2c3bf4390.png)

**Comment by thejameskyle** [comment]
I like the yellow one personally. @sebmck ?

**Comment by sebmck** [comment]
@thejameskyle @sparty02 Not fussed.

**Comment by sparty02** [comment]
Yellow pops better.... I'll go with that.

**Comment by thejameskyle** [comment]
Sweet! Thanks @sparty02
