### ISSUE TITLE
Is 6-to-library worth spreading the word?

### ISSUE THREAD

**Issue by tomekwi** [6to5/6to5.github.io#35]
Hello,

I wrote the formatter [6-to-library](https://github.com/tomekwi/6-to-library.js). Do you think it's worth a mention somewhere in the docs?

##### Why?

I wanted to author in ES6, and still deliver a seamless experience to users today. The UMD formatter does its job well. But it has no support for simple globals, and always exports exports by name. I wanted to avoid the need for explicitly saying `require('a-library').default` when only the default key is exported.

**Comment by sebmck** [comment]
Actually as of 6to5/6to5#379 the AMD/UMD module formatter exports directly with defaults. 6to5 was going to add support for globals (see https://github.com/6to5/6to5/issues/119#issuecomment-61430514) but there were various issues associated with it.

**Comment by tomekwi** [comment]
Alright, now looking at your tests it seems like I have picked up something you had been working on in parallel. Bad luck :)

BTW, it's a lot cleaner than my solution. Impressive how quickly 6to5 develops. Thumbs up!

**Comment by sebmck** [comment]
Thanks for your work though @tomekwi! I'll check out your globals stuff as I haven't currently implemented that and I'd be interested to see how it works.

**Comment by tomekwi** [comment]
@sebmck, I've simply chosen to name the export/import after the filename. This approach isn't explicit, but works out of the box – also when you have mutiple modules in your app.

When you need to import a library by another name, you use the syntax `import _ from "lodash"`. I think it's quite natural, just as `import $ from "jquery"` or `import m from "mithril"` anyway.

You can still `import {default as _} from "lodash"` if you really want the `global.lodash`.
