### ISSUE TITLE
REPL output doesn't match command line output

### ISSUE THREAD

**Issue by kevinb7** [6to5/6to5.github.io#57]
Given this code:
```
class User extends Model {
  constructor() {
    super();
    this.sayHello();
  }

  sayHello() {
    alert("Hello World!");
  }
}
```

The REPL should produce:
```
var User = function User() {
  Model.call(this);
  this.sayHello();
};

_inherits(User, Model);

User.prototype.sayHello = function () {
  alert("Hello World!");
};
```

It actually produces:
```
var User = (function (Model) {
  function User() {
    _get(Object.getPrototypeOf(User.prototype), "constructor", this).call(this);
    this.sayHello();
  }

  _inherits(User, Model);

  _prototypeProperties(User, null, {
    sayHello: {
      value: function () {
        alert("Hello World!");
      },
      writable: true,
      enumerable: true,
      configurable: true
    }
  });

  return User;
})(Model);
```

**Comment by sebmck** [comment]
It shouldn't. This is to maintain spec compliancy with prototype changes etc 6to5/6to5#408. You can get this output by setting loose mode on classes. `$ 6to5 --loose classes`. Also see #40 for the issue tracking changing the code example.

**Comment by kevinb7** [comment]
Skimming 408 cleared things up for me.  I was confused when you said I was using an "outdated version of 6to5" in the other thread because I thought you meant that my "browser.js" was out of date.  I checked the command line version and sure enough it's sitting at "1.15.0".  I'm doing the ES6 playground site for education purposes so I'd like to show simpler transform just so they have a basic idea of what's going on.  I'm doing ```to5.transform(code, { loose: "classes" });``` and it's working.  I'll let people know that they can use this option if they really care about the readability of the output code.  Thanks for your help this evening.

**Comment by sebmck** [comment]
@kevinb7 No problem! Sorry for not being more clear. I'm currently working on adding some documentation on loose mode as there's quite a bit to document as it makes the transformers not output 100% spec compliant code, it will however output code that works for the 99% use cases and is thus much faster.

**Comment by kevinb7** [comment]
@sebmck No worries.  It's good to know about the performance impacts as well.  Thanks!
