### ISSUE TITLE
Add cache busting

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5.github.io#6]
`?t=timestamp` at the end of all the resources.

**Comment by sparty02** [comment]
@thejameskyle , did you have other resources in mind outside of what has been changed with f4729a58d7b4ff2687b288c2625dbc1e03c9320f ?

**Comment by sparty02** [comment]
Note to self: Github pages only allows the use of a select few Jekyll plugins out of the box.  Unfortunately the jekyll-assets plugin isn't one of them, so we'll need a different solution (e.g. like the ?t=timestamp suggestion @thejameskyle originally suggested!)   :smirk:
