### ISSUE TITLE
"no runtime"?

### ISSUE THREAD

**Issue by Daniel15** [6to5/6to5.github.io#70]
The 6to5 site states:
> Maps directly to the equivalent ES5 with no runtime

What does "no runtime" mean in this context? When I use ES6 class syntax I get a few extra helpers in the generated code:
```javascript
var _get = function get(object, property, receiver) {
  var desc = Object.getOwnPropertyDescriptor(object, property);

  if (desc === undefined) {
    var parent = Object.getPrototypeOf(object);

    if (parent === null) {
      return undefined;
    } else {
      return get(parent, property, receiver);
    }
  } else if ("value" in desc && desc.writable) {
    return desc.value;
  } else {
    var getter = desc.get;
    if (getter === undefined) {
      return undefined;
    }
    return getter.call(receiver);
  }
};

var _inherits = function (subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
  }
  subClass.prototype = Object.create(superClass && superClass.prototype, {
    constructor: {
      value: subClass,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });
  if (superClass) subClass.__proto__ = superClass;
};

var _prototypeProperties = function (child, staticProps, instanceProps) {
  if (staticProps) Object.defineProperties(child, staticProps);
  if (instanceProps) Object.defineProperties(child.prototype, instanceProps);
};
```

Admittedly this is a very small amount of extra code, but is that code not considered a "runtime"? If not, what would you consider to be a runtime? Do you mean some actual sort of VM?

**Comment by sebmck** [comment]
By "no runtime" it just means that you don't need to include a 80KB blob as with Traceur etc. Basically instead of having a very heavy runtime/polyfill 6to5 will insert lightweight helpers.

Relevant section from [Compare](http://6to5.org/docs/compare/).

> Sometimes there are little inline functions that 6to5 needs. These are placed at the top of your file much like coffee-script does. If these bother you then you can use the [optional runtime](http://6to5.org/docs/usage/runtime). We promise that these inline functions will never be significant and will always be used as little as possible.

These helper functions are only really excessive in the case of classes. It's due to needing to be 100% spec compliant. You can alternatively use [loose mode](http://6to5.org/docs/usage/loose/) that has some caveats but outputs [significantly reduced code](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=true&code=class%20Foo%20%7B%0A%20%20%0A%7D%0A%0Aclass%20Bar%20extends%20Foo%20%7B%0A%20%20%0A%7D).

**Comment by sebmck** [comment]
I feel like I dodged the question a bit but in the context of "no runtime" it refers to the inclusion of an external script in order for your transpiled code to work.

**Comment by Daniel15** [comment]
Thanks for the quick response @sebmck, I really appreciate it :) 

I've never used Traceur before so I didn't know that it had a heavy runtime like that. I'm considering trying out 6to5 rather than Facebook's JSXTransformer/jstransform as 6to5 is more complete with its ES6 features.

> I feel like I dodged the question a bit but in the context of "no runtime" it refers to the inclusion of an external script in order for your transpiled code to work.

Your answer totally made sense to me. However I think it'd be good to change the site from "no runtime" to "no external scripts" or something like that to clarify it for n00bs like me. I'm used to "runtime" referring to a VM or something similar, rather than just meaning an external chunk of code.

**Comment by sebmck** [comment]
@Daniel15 

> I think it'd be good to change the site from "no runtime" to "no external scripts" or something like that to clarify it for n00bs like me. I'm used to "runtime" referring to a VM or something similar, rather than just meaning an external chunk of code.

Ah yeah that's true. The site currently needs some work done on copytext as there have been some changes lately that have made it a bit flaky. I'm not very used to writing technical documentation so I have difficulty simplifying concepts, definently hope to fix it up soon. Thanks for bringing it to my attention though!
