### ISSUE TITLE
FR: Local storage for REPL.

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5.github.io#71]
Was planning to add this feature of saving `input.editor.getValue();` to localstore. 

If `query.code` found display it or else fetch and display the local store data.

What say @sebmck @thejameskyle ?

**Comment by thejameskyle** [comment]
Possibly, I'll look into it

**Comment by hemanth** [comment]
:+1: Eger to help :)

**Comment by thejameskyle** [comment]
@hemanth Go ahead and take this if you want :)

**Comment by hemanth** [comment]
@sparty02 Shall I cheery pick the changes?

**Comment by sparty02** [comment]
@hemanth Go for it!

**Comment by hemanth** [comment]
@sparty02 @thejameskyle @sebmck Done!

**Comment by hemanth** [comment]
This got in. :bowtie:
