### ISSUE TITLE
Needs more information: How does one selectively include polyfills?

### ISSUE THREAD

**Issue by goatslacker** [6to5/6to5.github.io#76]
This statement 

> You may alternatively selectively include what you need:

which can be found in the [polyfills section](http://6to5.org/docs/usage/caveats/) needs some clarification. 

How would one go about selectively including what you need? Do you hunt for the packages yourself? It doesn't seem possible with 6to5 but it would be nice perhaps as a part of https://github.com/zloirock/core-js

**Comment by sebmck** [comment]
@goatslacker You'll have to hunt down the specific polyfills yourself. So [Array.from](https://github.com/mathiasbynens/Array.from), [es6-symbol](https://github.com/medikoo/es6-symbol) etc. The only downside is that these wont play very well together as they're usually very opinionated and only provide a subset. You can already create custom `core-js` builds but I think it's important to note that the entirety of `core-js` is only ~23KB without gzip. You'll most likely run into interoperability issues with various shims and polyfills.

**Comment by goatslacker** [comment]
If core.js supported it, would 6to5 be open to something like `require("6to5/polyfill/symbol");`?

**Comment by sebmck** [comment]
@goatslacker Potentially. I recall there being a suggestion for making `core-js` modular but it'd require significant architectural changes. /cc @zloirock
