### ISSUE TITLE
REPL fails to update URL hash when the code throws an error

### ISSUE THREAD

**Issue by hawkrives** [6to5/6to5.github.io#88]
At least, when I paste this

```js
if (let x = 5) { console.log(x) }
```

into the REPL, the url never changes, and the left side throws an error.

on Chrome 39.0.2171.99 (and some version of Chrome 40 < 40.0.2214.91)

**Comment by hawkrives** [comment]
@chicoxyzzy Did you see the same problem on Chrome 40.0.2214.91?

**Comment by chicoxyzzy** [comment]
yes same issue

**Comment by thejameskyle** [comment]
Fixed! Thanks for reporting this.
